version: "3"

services:
  server:
    build: server/
    volumes:
      - servervol:/serverdata
    
    networks:
      - nooliNetwork
  
  client:
    build: client/
    volumes:
      - clientvol:/clientdata
    depends_on:
      - server
    networks:
      - nooliNetwork

volumes:
  servervol:
  clientvol:

networks:
  nooliNetwork:
    driver: bridge